"""
Constants for Airlock Common
"""
from .api import (
    API_VERSION,
    API_PREFIX,
    HEALTH_ENDPOINT,
    LIVE_ENDPOINT,
    READY_ENDPOINT,
)
from .status import (
    HTTP_STATUS_OK,
    HTTP_STATUS_CREATED,
    HTTP_STATUS_BAD_REQUEST,
    HTTP_STATUS_UNAUTHORIZED,
    HTTP_STATUS_FORBIDDEN,
    HTTP_STATUS_NOT_FOUND,
    HTTP_STATUS_CONFLICT,
    HTTP_STATUS_INTERNAL_SERVER_ERROR,
    HTTP_STATUS_SERVICE_UNAVAILABLE,
)
from .errors import (
    ERROR_CODE_VALIDATION_ERROR,
    ERROR_CODE_NOT_FOUND,
    ERROR_CODE_UNAUTHORIZED,
    ERROR_CODE_FORBIDDEN,
    ERROR_CODE_CONFLICT,
    ERROR_CODE_INTERNAL_SERVER_ERROR,
    ERROR_CODE_SERVICE_UNAVAILABLE,
)
from .roles import (
    ROLE_SUBMITTER,
    ROLE_REVIEWER,
    ROLE_ADMIN,
    ROLES,
)

__all__ = [
    "API_VERSION",
    "API_PREFIX",
    "HEALTH_ENDPOINT",
    "LIVE_ENDPOINT",
    "READY_ENDPOINT",
    "HTTP_STATUS_OK",
    "HTTP_STATUS_CREATED",
    "HTTP_STATUS_BAD_REQUEST",
    "HTTP_STATUS_UNAUTHORIZED",
    "HTTP_STATUS_FORBIDDEN",
    "HTTP_STATUS_NOT_FOUND",
    "HTTP_STATUS_CONFLICT",
    "HTTP_STATUS_INTERNAL_SERVER_ERROR",
    "HTTP_STATUS_SERVICE_UNAVAILABLE",
    "ERROR_CODE_VALIDATION_ERROR",
    "ERROR_CODE_NOT_FOUND",
    "ERROR_CODE_UNAUTHORIZED",
    "ERROR_CODE_FORBIDDEN",
    "ERROR_CODE_CONFLICT",
    "ERROR_CODE_INTERNAL_SERVER_ERROR",
    "ERROR_CODE_SERVICE_UNAVAILABLE",
    "ROLE_SUBMITTER",
    "ROLE_REVIEWER",
    "ROLE_ADMIN",
    "ROLES",
]

