"""
Error codes for Airlock Common
"""

# Error Codes
ERROR_CODE_VALIDATION_ERROR = "VALIDATION_ERROR"
ERROR_CODE_NOT_FOUND = "NOT_FOUND"
ERROR_CODE_UNAUTHORIZED = "UNAUTHORIZED"
ERROR_CODE_FORBIDDEN = "FORBIDDEN"
ERROR_CODE_CONFLICT = "CONFLICT"
ERROR_CODE_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
ERROR_CODE_SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

