"""
HTTP status codes for Airlock Common
"""

# Success Status Codes
HTTP_STATUS_OK = 200
HTTP_STATUS_CREATED = 201

# Client Error Status Codes
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_UNAUTHORIZED = 401
HTTP_STATUS_FORBIDDEN = 403
HTTP_STATUS_NOT_FOUND = 404
HTTP_STATUS_CONFLICT = 409

# Server Error Status Codes
HTTP_STATUS_INTERNAL_SERVER_ERROR = 500
HTTP_STATUS_SERVICE_UNAVAILABLE = 503

